name: Faith Tabernacle Admin Development Pipeline

on:
  push:
    branches: [ develop ]

jobs:

#### Run the android build and ios build concurrently ####
#ANDROID BUILD
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install app dependencies
        run: npm install --legacy-peer-deps

      - name: Build Files
        run: npm run build

      - name: Upload dev APK
        uses: actions/upload-artifact@v3
        with:
          name: admin-app
          path: dist/
  
  deploy:
    name: Deploy App
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: admin-app
          path: project
      - name: Copy Artifact to Server
        uses: garygrossgarten/github-action-scp@v0.5.3
        with: 
          local: project
          remote: /www/wwwroot/admin
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          rmRemote: true

#Deploy both Android and Ios if previous steps are successful
  # deploy:
  #   name: Deploy Android App - Firebase
  #   needs: [build-android, build-ios]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download Artifact
  #       uses: actions/download-artifact@v2
  #       with: 
  #         name: app-dev
  #         path: project/apk

  #     - name: upload artifact to Firebase
  #       uses: wzieba/Firebase-Distribution-Github-Action@v1
  #       with:
  #         appId: ${{secrets.FIREBASE_ANDROID_ID}}
  #         token: ${{secrets.FIREBASE_TOKEN}}
  #         groups: developers-android
  #         file: project/apk/app-debug.apk
  #         debug: false #this will show the verbose log